apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aether-track.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aether-track
  template:
    metadata:
      labels:
        app: aether-track
    spec:
      containers:
        - name: aether-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          # --- REAL WORLD STANDARD: ENV FROM SECRETS ---
          env:
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: aether-secrets
                  key: weather-api-key
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: aether-secrets
                  key: gemini-api-key
          # ---------------------------------------------
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
